name: Build

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-lastest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          cd ${{ env.BASE_DIR}}
          python3 -m pip install --upgrade pip
          python3 -m pip install -r req.txt
          python3 manage.py collectstatic --no-input

      - name: Setup Pack CLI
        uses: buildpacks/github-actions/setup-pack@v5.0.0

      - name: Build app using Buildpacks
        run: |
          pack build ${{ env.DOCKER_HUB_REPO }}:${{ env.DOCKER_HUB_IMAGE_TAG }} \
            --path ${{ env.BASE_DIR }} \
            --env "DISABLE_COLLECTSTATIC=1" \
            --builder ${{ env.BUILDPACK_BUILDER }}

      - name: Login to Docker Hub
        id: docker_login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Check Docker Login
        if: steps.docker_login.outcome == 'failure'
        run: |
          echo "Failed to log in to Docker Hub. Please check your credentials."
          exit 1

      - name: Tag the container as latest as well specific version
        run: |
          docker tag ${{ env.DOCKER_HUB_REPO }}:${{ env.DOCKER_HUB_IMAGE_TAG }} ${{ env.DOCKER_HUB_REPO }}:latest

      - name: Push the specific version and latest tag to Docker Hub
        run: docker push ${{ env.DOCKER_HUB_REPO }} --all-tags
